/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_microsoft_applicationinsights_agent_bootstrap_diagnostics_etw_EtwProvider */

#ifndef _Included_com_microsoft_applicationinsights_agent_bootstrap_diagnostics_etw_EtwProvider
#define _Included_com_microsoft_applicationinsights_agent_bootstrap_diagnostics_etw_EtwProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_microsoft_applicationinsights_agent_bootstrap_diagnostics_etw_EtwProvider
 * Method:    cppWriteEvent
 * Signature: (Lcom/microsoft/applicationinsights/agent/bootstrap/diagnostics/etw/events/model/IpaEtwEventBase;)V
 */
JNIEXPORT void JNICALL Java_com_microsoft_applicationinsights_agent_bootstrap_diagnostics_etw_EtwProvider_cppWriteEvent
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
