/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.microsoft.applicationinsights.etw_testapp;

import org.junit.Test;
import static org.junit.Assert.*;

public class EtwTestAppTest {
    @Test
    public void testRootPage() {
    }
}
