/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.microsoft.applicationinsights.etw_testapp;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;

@SpringBootApplication
public class EtwTestApp extends SpringBootServletInitializer {

    public EtwTestApp() {
        super();
        setRegisterErrorPageFilter(false);
    }

    public static void main(String[] args) {
        SpringApplication.run(EtwTestApp.class, args);
    }
}
