//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// 
//     Tool     : bondc, Version=3.0.1, Build=bond-git.retail.not
//     Template : Microsoft.Bond.Rules.dll#Java.tt
//     File     : com\microsoft\applicationinsights\extensibility\model\AjaxCallData.java
//
//     Changes to this file may cause incorrect behavior and will be lost when
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
package com.microsoft.applicationinsights.extensibility.model;


import com.microsoft.applicationinsights.implementation.schemav2.PageViewData;

/*** *****************************************************************************
 * AjaxCall type
 * *****************************************************************************
 * Instances of AjaxCall represent a remote call from JavaScript on the client  to the server
*/
@SuppressWarnings("all")
public class AjaxCallData extends PageViewData {
    //
    // Fields
    //

    // 10: Required string ajaxUrl
    private String ajaxUrl;

    // 20: Required double requestSize
    private double requestSize;

    // 30: Required double responseSize
    private double responseSize;

    // 40: Required string timeToFirstByte
    private String timeToFirstByte;

    // 50: Required string timeToLastByte
    private String timeToLastByte;

    // 60: Required string callbackDuration
    private String callbackDuration;

    // 70: Required string responseCode
    private String responseCode;

    // 80: Required bool success
    private boolean success;

    /**
     * @return current value of ajaxUrl property
     */
    public final String getAjaxUrl() {
        return this.ajaxUrl;
    }

    /**
     * @param value new value of ajaxUrl property
     */
    public final void setAjaxUrl(String value) {
        this.ajaxUrl = value;
    }

    /**
     * @return current value of requestSize property
     */
    public final double getRequestSize() {
        return this.requestSize;
    }

    /**
     * @param value new value of requestSize property
     */
    public final void setRequestSize(double value) {
        this.requestSize = value;
    }

    /**
     * @return current value of responseSize property
     */
    public final double getResponseSize() {
        return this.responseSize;
    }

    /**
     * @param value new value of responseSize property
     */
    public final void setResponseSize(double value) {
        this.responseSize = value;
    }

    /**
     * @return current value of timeToFirstByte property
     */
    public final String getTimeToFirstByte() {
        return this.timeToFirstByte;
    }

    /**
     * @param value new value of timeToFirstByte property
     */
    public final void setTimeToFirstByte(String value) {
        this.timeToFirstByte = value;
    }

    /**
     * @return current value of timeToLastByte property
     */
    public final String getTimeToLastByte() {
        return this.timeToLastByte;
    }

    /**
     * @param value new value of timeToLastByte property
     */
    public final void setTimeToLastByte(String value) {
        this.timeToLastByte = value;
    }

    /**
     * @return current value of callbackDuration property
     */
    public final String getCallbackDuration() {
        return this.callbackDuration;
    }

    /**
     * @param value new value of callbackDuration property
     */
    public final void setCallbackDuration(String value) {
        this.callbackDuration = value;
    }

    /**
     * @return current value of responseCode property
     */
    public final String getResponseCode() {
        return this.responseCode;
    }

    /**
     * @param value new value of responseCode property
     */
    public final void setResponseCode(String value) {
        this.responseCode = value;
    }

    /**
     * @return current value of success property
     */
    public final boolean getSuccess() {
        return this.success;
    }

    /**
     * @param value new value of success property
     */
    public final void setSuccess(boolean value) {
        this.success = value;
    }

    // Constructor
    public AjaxCallData()
    {
    }

    /*
     * @see com.microsoft.bond.BondSerializable#reset()
     */
    public void reset() {
        reset("AjaxCallData", "com.microsoft.applicationinsights.extensibility.model.AjaxCallData");
    }

    protected void reset(String name, String qualifiedName) {
        ajaxUrl = "";
        requestSize = 0;
        responseSize = 0;
        timeToFirstByte = "";
        timeToLastByte = "";
        callbackDuration = "";
        responseCode = "";
        success = false;
    }
} // class AjaxCallData
