



//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// 
//     Tool     : bondc, Version=3.0.1, Build=bond-git.retail.not
//     Template : Microsoft.Bond.Rules.dll#Java.tt
//     File     : com\microsoft\applicationinsights\extensibility\model\DependencyKind.java
//
//     Changes to this file may cause incorrect behavior and will be lost when
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
package com.microsoft.applicationinsights.extensibility.model;


/**
* DependencyKind
*/
public enum DependencyKind {
    SQL(0),
    HTTP(1),
    Other(2),
    __INVALID_ENUM_VALUE(3);

    private final int value;

    DependencyKind(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public static DependencyKind fromValue(int value) {
        switch (value) {
            case 0:
                return SQL;
            case 1:
                return HTTP;
            case 2:
                return Other;
        }
        return __INVALID_ENUM_VALUE;
    }
} // enum DependencyKind

