//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// 
//     Tool     : bondc, Version=3.0.1, Build=bond-git.retail.not
//     Template : Microsoft.Bond.Rules.dll#Java.tt
//     File     : com\microsoft\applicationinsights\extensibility\model\EventData.java
//
//     Changes to this file may cause incorrect behavior and will be lost when
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
package com.microsoft.applicationinsights.extensibility.model;


/**
 * *****************************************************************************                                Event type***************************************************************************** Instances of Event represent structured event records that can be grouped    and searched by their properties.    More complex events, like ETW, will most likely be represented by Part C     extensions of Event.
 */
@SuppressWarnings("all")
public class EventData
{
    //
    // Fields
    //

    // 10: Required int32 ver
    private int ver;

    // 20: Required string name
    private String name;

    // 100: Optional map<string, string> properties
    private java.util.HashMap<String, String> properties;

    // 200: Optional map<string, double> measurements
    private java.util.HashMap<String, Double> measurements;

    // Constructor
    public EventData()
    {
        reset();
    }

    /**
     * @return current value of ver property
     */
    public final int getVer()
    {
        return this.ver;
    }

    /**
     * @param value new value of ver property
     */
    public final void setVer(int value)
    {
        this.ver = value;
    }

    /**
     * @return current value of name property
     */
    public final String getName()
    {
        return this.name;
    }

    /**
     * @param value new value of name property
     */
    public final void setName(String value)
    {
        this.name = value;
    }

    /**
     * @return current value of properties property
     */
    public final java.util.HashMap<String, String> getProperties()
    {
        return this.properties;
    }

    /**
     * @param value new value of properties property
     */
    public final void setProperties(java.util.HashMap<String, String> value)
    {
        this.properties = value;
    }

    /**
     * @return current value of measurements property
     */
    public final java.util.HashMap<String, Double> getMeasurements()
    {
        return this.measurements;
    }

    /**
     * @param value new value of measurements property
     */
    public final void setMeasurements(java.util.HashMap<String, Double> value)
    {
        this.measurements = value;
    }

    /*
     * @see com.microsoft.bond.BondSerializable#reset()
     */
    public void reset()
    {
        reset("EventData", "com.microsoft.applicationinsights.extensibility.model.EventData");
    }

    protected void reset(String name, String qualifiedName)
    {

        ver = 1;
        this.name = "";
        if (properties == null)
        {
            properties = new java.util.HashMap<String, String>();
        }
        else
        {
            properties.clear();
        }
        if (measurements == null)
        {
            measurements = new java.util.HashMap<String, Double>();
        }
        else
        {
            measurements.clear();
        }
    }
} // class EventData
