//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// 
//     Tool     : bondc, Version=3.0.1, Build=bond-git.retail.not
//     Template : Microsoft.Bond.Rules.dll#Java.tt
//     File     : com\microsoft\applicationinsights\extensibility\model\ExceptionDetails.java
//
//     Changes to this file may cause incorrect behavior and will be lost when
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
package com.microsoft.applicationinsights.extensibility.model;


/**
* ExceptionDetails
*/
@SuppressWarnings("all")
public class ExceptionDetails {
    //
    // Fields
    //

    // 10: Optional int32 id
    private int id;

    // 20: Optional int32 outerId
    private int outerId;

    // 30: Required string typeName
    private String typeName;

    // 40: Required string message
    private String message;

    // 50: Optional bool hasFullStack
    private boolean hasFullStack;

    // 60: Optional string stack
    private String stack;

    // 70: Optional vector<com.microsoft.applicationinsights.extensibility.model.StackFrame> parsedStack
    private java.util.ArrayList<com.microsoft.applicationinsights.extensibility.model.StackFrame> parsedStack;

    /**
     * @return current value of id property
     */
    public final int getId() {
        return this.id;
    }

    /**
     * @param value new value of id property
     */
    public final void setId(int value) {
        this.id = value;
    }

    /**
     * @return current value of outerId property
     */
    public final int getOuterId() {
        return this.outerId;
    }

    /**
     * @param value new value of outerId property
     */
    public final void setOuterId(int value) {
        this.outerId = value;
    }

    /**
     * @return current value of typeName property
     */
    public final String getTypeName() {
        return this.typeName;
    }

    /**
     * @param value new value of typeName property
     */
    public final void setTypeName(String value) {
        this.typeName = value;
    }

    /**
     * @return current value of message property
     */
    public final String getMessage() {
        return this.message;
    }

    /**
     * @param value new value of message property
     */
    public final void setMessage(String value) {
        this.message = value;
    }

    /**
     * @return current value of hasFullStack property
     */
    public final boolean getHasFullStack() {
        return this.hasFullStack;
    }

    /**
     * @param value new value of hasFullStack property
     */
    public final void setHasFullStack(boolean value) {
        this.hasFullStack = value;
    }

    /**
     * @return current value of stack property
     */
    public final String getStack() {
        return this.stack;
    }

    /**
     * @param value new value of stack property
     */
    public final void setStack(String value) {
        this.stack = value;
    }

    /**
     * @return current value of parsedStack property
     */
    public final java.util.ArrayList<com.microsoft.applicationinsights.extensibility.model.StackFrame> getParsedStack() {
        return this.parsedStack;
    }

    /**
     * @param value new value of parsedStack property
     */
    public final void setParsedStack(java.util.ArrayList<com.microsoft.applicationinsights.extensibility.model.StackFrame> value) {
        this.parsedStack = value;
    }
    // Constructor
    public ExceptionDetails() {
        reset();
    }

    /*
     * @see com.microsoft.bond.BondSerializable#reset()
     */
    public void reset() {
        reset("ExceptionDetails", "com.microsoft.applicationinsights.extensibility.model.ExceptionDetails");
    }

    protected void reset(String name, String qualifiedName) {
        
        id = 0;
        outerId = 0;
        typeName = "";
        message = "";
        hasFullStack = true;
        stack = "";
        if (parsedStack == null) {
            parsedStack = new java.util.ArrayList<com.microsoft.applicationinsights.extensibility.model.StackFrame>();
        } else {
            parsedStack.clear();
        }
    }
} // class ExceptionDetails
