//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// 
//     Tool     : bondc, Version=3.0.1, Build=bond-git.retail.not
//     Template : Microsoft.Bond.Rules.dll#Java.tt
//     File     : com\microsoft\applicationinsights\extensibility\model\MetricData.java
//
//     Changes to this file may cause incorrect behavior and will be lost when
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
package com.microsoft.applicationinsights.extensibility.model;


/**
* Instance of the Metric item is a list of measurements (single    data points) and/or aggregations
*/
@SuppressWarnings("all")
public class MetricData
{
    //
    // Fields
    //

    // 10: Required int32 ver
    private int ver;

    // 20: Required vector<com.microsoft.applicationinsights.extensibility.model.DataPoint> metrics
    private java.util.ArrayList<com.microsoft.applicationinsights.extensibility.model.DataPoint> metrics;

    // 100: Optional map<string, string> properties
    private java.util.HashMap<String, String> properties;

    /**
     * @return current value of ver property
     */
    public final int getVer() {
        return this.ver;
    }

    /**
     * @param value new value of ver property
     */
    public final void setVer(int value) {
        this.ver = value;
    }

    /**
     * @return current value of metrics property
     */
    public final java.util.ArrayList<com.microsoft.applicationinsights.extensibility.model.DataPoint> getMetrics() {
        return this.metrics;
    }

    /**
     * @param value new value of metrics property
     */
    public final void setMetrics(java.util.ArrayList<com.microsoft.applicationinsights.extensibility.model.DataPoint> value) {
        this.metrics = value;
    }

    /**
     * @return current value of properties property
     */
    public final java.util.HashMap<String, String> getProperties() {
        return this.properties;
    }

    /**
     * @param value new value of properties property
     */
    public final void setProperties(java.util.HashMap<String, String> value) {
        this.properties = value;
    }

    // Constructor
    public MetricData() {
        reset();
    }

    /*
     * @see com.microsoft.bond.BondSerializable#reset()
     */
    public void reset() {
        reset("MetricData", "com.microsoft.applicationinsights.extensibility.model.MetricData");
    }

    protected void reset(String name, String qualifiedName) {
        
        ver = 1;
        if (metrics == null) {
            metrics = new java.util.ArrayList<com.microsoft.applicationinsights.extensibility.model.DataPoint>();
        } else {
            metrics.clear();
        }
        if (properties == null) {
            properties = new java.util.HashMap<String, String>();
        } else {
            properties.clear();
        }
    }
} // class MetricData
