//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// 
//     Tool     : bondc, Version=3.0.1, Build=bond-git.retail.not
//     Template : Microsoft.Bond.Rules.dll#Java.tt
//     File     : com\microsoft\applicationinsights\extensibility\model\PageViewPerfData.java
//
//     Changes to this file may cause incorrect behavior and will be lost when
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
package com.microsoft.applicationinsights.extensibility.model;


/**
* *****************************************************************************                                 PageViewPerf type ***************************************************************************** Instance of PageView represents    - page view with no performance data    - page view with performance data    - just the performance data of an earlier page request
*/
@SuppressWarnings("all")
public class PageViewPerfData extends com.microsoft.applicationinsights.extensibility.model.PageViewData {
    //
    // Fields
    //

    // 10: Optional string perfTotal
    private String perfTotal;

    // 20: Optional string networkConnect
    private String networkConnect;

    // 30: Optional string sentRequest
    private String sentRequest;

    // 40: Optional string receivedResponse
    private String receivedResponse;

    // 50: Optional string domProcessing
    private String domProcessing;

    /**
     * @return current value of perfTotal property
     */
    public final String getPerfTotal() {
        return this.perfTotal;
    }

    /**
     * @param value new value of perfTotal property
     */
    public final void setPerfTotal(String value) {
        this.perfTotal = value;
    }

    /**
     * @return current value of networkConnect property
     */
    public final String getNetworkConnect() {
        return this.networkConnect;
    }

    /**
     * @param value new value of networkConnect property
     */
    public final void setNetworkConnect(String value) {
        this.networkConnect = value;
    }

    /**
     * @return current value of sentRequest property
     */
    public final String getSentRequest() {
        return this.sentRequest;
    }

    /**
     * @param value new value of sentRequest property
     */
    public final void setSentRequest(String value) {
        this.sentRequest = value;
    }

    /**
     * @return current value of receivedResponse property
     */
    public final String getReceivedResponse() {
        return this.receivedResponse;
    }

    /**
     * @param value new value of receivedResponse property
     */
    public final void setReceivedResponse(String value) {
        this.receivedResponse = value;
    }

    /**
     * @return current value of domProcessing property
     */
    public final String getDomProcessing() {
        return this.domProcessing;
    }

    /**
     * @param value new value of domProcessing property
     */
    public final void setDomProcessing(String value) {
        this.domProcessing = value;
    }

    // Constructor
    public PageViewPerfData() {
        
    }

    /*
     * @see com.microsoft.bond.BondSerializable#reset()
     */
    public void reset() {
        reset("PageViewPerfData", "com.microsoft.applicationinsights.extensibility.model.PageViewPerfData");
    }

    protected void reset(String name, String qualifiedName) {
        super.reset(name, qualifiedName);
        perfTotal = "";
        networkConnect = "";
        sentRequest = "";
        receivedResponse = "";
        domProcessing = "";
    }
} // class PageViewPerfData
