//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// 
//     Tool     : bondc, Version=3.0.1, Build=bond-git.retail.not
//     Template : Microsoft.Bond.Rules.dll#Java.tt
//     File     : com\microsoft\applicationinsights\extensibility\model\RddSourceType.java
//
//     Changes to this file may cause incorrect behavior and will be lost when
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
package com.microsoft.applicationinsights.extensibility.model;


/**
* *****************************************************************************                                Remote Dependency type***************************************************************************** Instance of Remote Dependecy represents a metric that was collected     specifically for an interaction of the monitored component with a remote     component/service like SQL
*/
public enum RddSourceType {
    None(0),
    Aic(1),
    Apmc(2),
    __INVALID_ENUM_VALUE(3);

    private final int value;

    RddSourceType(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public static RddSourceType fromValue(int value) {
        switch (value) {
            case 0:
                return None;
            case 1:
                return Aic;
            case 2:
                return Apmc;
        }
        return __INVALID_ENUM_VALUE;
    }
} // enum RddSourceType

