//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// 
//     Tool     : bondc, Version=3.0.1, Build=bond-git.retail.not
//     Template : Microsoft.Bond.Rules.dll#Java.tt
//     File     : com\microsoft\applicationinsights\extensibility\model\RemoteDependencyData.java
//
//     Changes to this file may cause incorrect behavior and will be lost when
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
package com.microsoft.applicationinsights.extensibility.model;


/**
* RemoteDependencyData
*/
@SuppressWarnings("all")
public class RemoteDependencyData extends com.microsoft.applicationinsights.extensibility.model.DataPoint {
    //
    // Fields
    //

    // 10: Required int32 ver
    private int ver;

    // 20: Required com.microsoft.applicationinsights.extensibility.model.DependencyKind dependencyKind
    private com.microsoft.applicationinsights.extensibility.model.DependencyKind dependencyKind;

    // 30: Optional nullable<bool> success
    private Boolean success;

    // 40: Optional nullable<bool> async
    private Boolean async;

    // 50: Optional com.microsoft.applicationinsights.extensibility.model.RddSourceType rddSource
    private com.microsoft.applicationinsights.extensibility.model.RddSourceType rddSource;

    // 100: Optional map<string, string> properties
    private java.util.HashMap<String, String> properties;

    /**
     * @return current value of ver property
     */
    public final int getVer() {
        return this.ver;
    }

    /**
     * @param value new value of ver property
     */
    public final void setVer(int value) {
        this.ver = value;
    }

    /**
     * @return current value of dependencyKind property
     */
    public final com.microsoft.applicationinsights.extensibility.model.DependencyKind getDependencyKind() {
        return this.dependencyKind;
    }

    /**
     * @param value new value of dependencyKind property
     */
    public final void setDependencyKind(com.microsoft.applicationinsights.extensibility.model.DependencyKind value) {
        this.dependencyKind = value;
    }

    /**
     * @return current value of success property
     */
    public final Boolean getSuccess() {
        return this.success;
    }

    /**
     * @param value new value of success property
     */
    public final void setSuccess(Boolean value) {
        this.success = value;
    }

    /**
     * @return current value of async property
     */
    public final Boolean getAsync() {
        return this.async;
    }

    /**
     * @param value new value of async property
     */
    public final void setAsync(Boolean value) {
        this.async = value;
    }

    /**
     * @return current value of rddSource property
     */
    public final com.microsoft.applicationinsights.extensibility.model.RddSourceType getRddSource() {
        return this.rddSource;
    }

    /**
     * @param value new value of rddSource property
     */
    public final void setRddSource(com.microsoft.applicationinsights.extensibility.model.RddSourceType value) {
        this.rddSource = value;
    }

    /**
     * @return current value of properties property
     */
    public final java.util.HashMap<String, String> getProperties() {
        return this.properties;
    }

    /**
     * @param value new value of properties property
     */
    public final void setProperties(java.util.HashMap<String, String> value) {
        this.properties = value;
    }

    // Constructor
    public RemoteDependencyData() {
        
    }

    /*
     * @see com.microsoft.bond.BondSerializable#reset()
     */
    public void reset() {
        reset("RemoteDependencyData", "com.microsoft.applicationinsights.extensibility.model.RemoteDependencyData");
    }

    protected void reset(String name, String qualifiedName) {
        super.reset(name, qualifiedName);
        ver = 1;
        dependencyKind = com.microsoft.applicationinsights.extensibility.model.DependencyKind.Other;
        success = null;
        async = null;
        rddSource = com.microsoft.applicationinsights.extensibility.model.RddSourceType.None;
        if (properties == null) {
            properties = new java.util.HashMap<String, String>();
        } else {
            properties.clear();
        }
    }
} // class RemoteDependencyData
