//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// 
//     Tool     : bondc, Version=3.0.1, Build=bond-git.retail.not
//     Template : Microsoft.Bond.Rules.dll#Java.tt
//     File     : com\microsoft\applicationinsights\extensibility\model\RequestData.java
//
//     Changes to this file may cause incorrect behavior and will be lost when
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
package com.microsoft.applicationinsights.extensibility.model;


/**
* *****************************************************************************                                Request type***************************************************************************** Instance of Request represents completion of an external request to the    application to do work, and contains a summary of that request execution    and the results.
*/
@SuppressWarnings("all")
public class RequestData
{
    //
    // Fields
    //

    // 10: Required int32 ver
    private int ver;

    // 20: Required string id
    private String id;

    // 30: Optional string name
    private String name;

    // 40: Required string startTime
    private String startTime;

    // 50: Required string duration
    private String duration;

    // 60: Required string responseCode
    private String responseCode;

    // 70: Required bool success
    private boolean success;

    // 80: Optional string httpMethod
    private String httpMethod;

    // 90: Optional string url
    private String url;

    // 100: Optional map<string, string> properties
    private java.util.HashMap<String, String> properties;

    // 200: Optional map<string, double> measurements
    private java.util.HashMap<String, Double> measurements;

    /**
     * @return current value of ver property
     */
    public final int getVer() {
        return this.ver;
    }

    /**
     * @param value new value of ver property
     */
    public final void setVer(int value) {
        this.ver = value;
    }

    /**
     * @return current value of id property
     */
    public final String getId() {
        return this.id;
    }

    /**
     * @param value new value of id property
     */
    public final void setId(String value) {
        this.id = value;
    }

    /**
     * @return current value of name property
     */
    public final String getName() {
        return this.name;
    }

    /**
     * @param value new value of name property
     */
    public final void setName(String value) {
        this.name = value;
    }

    /**
     * @return current value of startTime property
     */
    public final String getStartTime() {
        return this.startTime;
    }

    /**
     * @param value new value of startTime property
     */
    public final void setStartTime(String value) {
        this.startTime = value;
    }

    /**
     * @return current value of duration property
     */
    public final String getDuration() {
        return this.duration;
    }

    /**
     * @param value new value of duration property
     */
    public final void setDuration(String value) {
        this.duration = value;
    }

    /**
     * @return current value of responseCode property
     */
    public final String getResponseCode() {
        return this.responseCode;
    }

    /**
     * @param value new value of responseCode property
     */
    public final void setResponseCode(String value) {
        this.responseCode = value;
    }

    /**
     * @return current value of success property
     */
    public final boolean getSuccess() {
        return this.success;
    }

    /**
     * @param value new value of success property
     */
    public final void setSuccess(boolean value) {
        this.success = value;
    }

    /**
     * @return current value of httpMethod property
     */
    public final String getHttpMethod() {
        return this.httpMethod;
    }

    /**
     * @param value new value of httpMethod property
     */
    public final void setHttpMethod(String value) {
        this.httpMethod = value;
    }

    /**
     * @return current value of url property
     */
    public final String getUrl() {
        return this.url;
    }

    /**
     * @param value new value of url property
     */
    public final void setUrl(String value) {
        this.url = value;
    }

    /**
     * @return current value of properties property
     */
    public final java.util.HashMap<String, String> getProperties() {
        return this.properties;
    }

    /**
     * @param value new value of properties property
     */
    public final void setProperties(java.util.HashMap<String, String> value) {
        this.properties = value;
    }

    /**
     * @return current value of measurements property
     */
    public final java.util.HashMap<String, Double> getMeasurements() {
        return this.measurements;
    }

    /**
     * @param value new value of measurements property
     */
    public final void setMeasurements(java.util.HashMap<String, Double> value) {
        this.measurements = value;
    }

    // Constructor
    public RequestData() {
        reset();
    }

    /*
     * @see com.microsoft.bond.BondSerializable#reset()
     */
    public void reset() {
        reset("RequestData", "com.microsoft.applicationinsights.extensibility.model.RequestData");
    }

    protected void reset(String name, String qualifiedName) {
        
        ver = 1;
        id = "";
        this.name = "";
        startTime = "";
        duration = "";
        responseCode = "";
        success = false;
        httpMethod = "";
        url = "";
        if (properties == null) {
            properties = new java.util.HashMap<String, String>();
        } else {
            properties.clear();
        }
        if (measurements == null) {
            measurements = new java.util.HashMap<String, Double>();
        } else {
            measurements.clear();
        }
    }
} // class RequestData
