//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// 
//     Tool     : bondc, Version=3.0.1, Build=bond-git.retail.not
//     Template : Microsoft.Bond.Rules.dll#Java.tt
//     File     : com\microsoft\applicationinsights\extensibility\model\SeverityLevel.java
//
//     Changes to this file may cause incorrect behavior and will be lost when
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
package com.microsoft.applicationinsights.extensibility.model;


/**
* SeverityLevel
*/
public enum SeverityLevel {
    Verbose(0),
    Information(1),
    Warning(2),
    Error(3),
    Critical(4),
    __INVALID_ENUM_VALUE(5);

    private final int value;

    SeverityLevel(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public static SeverityLevel fromValue(int value) {
        switch (value) {
            case 0:
                return Verbose;
            case 1:
                return Information;
            case 2:
                return Warning;
            case 3:
                return Error;
            case 4:
                return Critical;
        }
        return __INVALID_ENUM_VALUE;
    }
} // enum SeverityLevel

