//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// 
//     Tool     : bondc, Version=3.0.1, Build=bond-git.retail.not
//     Template : Microsoft.Bond.Rules.dll#Java.tt
//     File     : com\microsoft\applicationinsights\extensibility\model\StackFrame.java
//
//     Changes to this file may cause incorrect behavior and will be lost when
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
package com.microsoft.applicationinsights.extensibility.model;


/**
* *****************************************************************************                                Exception type***************************************************************************** Instance of Exception represents handled or unhandled exception that occured    during execution of the monitored application.
*/
@SuppressWarnings("all")
public class StackFrame
{
    //
    // Fields
    //

    // 10: Required int32 level
    private int level;

    // 20: Required string method
    private String method;

    // 30: Optional string assembly
    private String assembly;

    // 50: Optional string fileName
    private String fileName;

    // 60: Optional int32 line
    private int line;

    /**
     * @return current value of level property
     */
    public final int getLevel() {
        return this.level;
    }

    /**
     * @param value new value of level property
     */
    public final void setLevel(int value) {
        this.level = value;
    }

    /**
     * @return current value of method property
     */
    public final String getMethod() {
        return this.method;
    }

    /**
     * @param value new value of method property
     */
    public final void setMethod(String value) {
        this.method = value;
    }

    /**
     * @return current value of assembly property
     */
    public final String getAssembly() {
        return this.assembly;
    }

    /**
     * @param value new value of assembly property
     */
    public final void setAssembly(String value) {
        this.assembly = value;
    }

    /**
     * @return current value of fileName property
     */
    public final String getFileName() {
        return this.fileName;
    }

    /**
     * @param value new value of fileName property
     */
    public final void setFileName(String value) {
        this.fileName = value;
    }

    /**
     * @return current value of line property
     */
    public final int getLine() {
        return this.line;
    }

    /**
     * @param value new value of line property
     */
    public final void setLine(int value) {
        this.line = value;
    }

    // Constructor
    public StackFrame() {
        reset();
    }

    /*
     * @see com.microsoft.bond.BondSerializable#reset()
     */
    public void reset() {
        reset("StackFrame", "com.microsoft.applicationinsights.extensibility.model.StackFrame");
    }

    protected void reset(String name, String qualifiedName) {
        
        level = 0;
        method = "";
        assembly = "";
        fileName = "";
        line = 0;
    }
} // class StackFrame
