name: Pull request helper
on:
  pull_request_target:

permissions:
  contents: write
  pull-requests: write

jobs:
  pull-request-helper:
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    uses: ./.github/workflows/reusable-regenerate-generated-files.yml
    with:
      pr_number: ${{ github.event.pull_request.number }}
      skip_if_contains_main: false
    secrets:
      PR_HELPER_GITHUB_TOKEN: ${{ secrets.PR_HELPER_GITHUB_TOKEN }}
